In [1]:
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd

In [ ]:
dataset=pd.read_csv("C:\\Users\\Avantika Singh\\Downloads\\reviews1.csv", delimiter='\t', quoting=3)

In [ ]:
import re
import pandas as pd
from nltk.stem import PorterStemmer

# Load your dataset (adjust the path as needed)
dataset = pd.read_csv("C:\\Users\\Avantika Singh\\Downloads\\reviews1.csv")

# Initialize the corpus and the Porter Stemmer
corpus = []
ps = PorterStemmer()

# Loop through the dataset
for i in range(len(dataset)):
    # Check if the review is not NaN
    if pd.notna(dataset['review'][i]):
        # Cleaning the review text
        zomato_ratings = re.sub('[^a-zA-Z]', ' ', dataset['review'][i])
        zomato_ratings = zomato_ratings.lower()
        zomato_ratings = zomato_ratings.split()
        
        # Stemming the words
        zomato_ratings = [ps.stem(word) for word in zomato_ratings]
        
        # Joining the stemmed words back into a single string
        zomato_ratings = ' '.join(zomato_ratings)
        
        # Appending the cleaned review to the corpus
        corpus.append(zomato_ratings)

# Now 'corpus' contains the cleaned and stemmed reviews
print(corpus)


['nice', 'best biryani so support staff of outlet person my order on call as i say full paisa vasool', 'deliveri boy wa veri decent and support', 'worst biryani i have tast in my life half of the biryani is in dustbin', 'all food is good and tasti will order again and lot more to explor in bawarchi s menu', 'shandar zabardast zindabad good go bawarchi keep it up', 'overal good experi will order again', 'good but cold of food', 'tasti food homestyl tasti preprat', 'love it', 'full paisa vasool tast me best bawarchi aur everest', 'good tast authent punjabi style matar paneer feel good to have such food in surat', 'veri tasti authent food', 'superb tasti asli dilli wala flavour', 'yummiest manchurian fri rice i have ever had in citi authent chines tast must order onc', 'veey tasti order again nd again', 'i have order manchurian fri rice but instead i got onli simpl fri rice feel like i am cheat by bawarchi restaur', 'veri bad not properli cook', 'delici', 'chines chees kulcha good fusion 

In [11]:
#Bags of word creation
from sklearn.feature_extraction.text import CountVectorizer

# Initialize the CountVectorizer with the desired max_features
cv = CountVectorizer(max_features=1600)

# Fit and transform the corpus into a feature array
X = cv.fit_transform(corpus).toarray()

# Assuming `y` is the last column in your dataset (such as a label or rating)
y = dataset.iloc[:, -1].values


In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler, MinMaxScaler

# 1. Load the dataset
file_path = 'C:\\Users\\Avantika Singh\\Downloads\\zomato_reviews.csv'  

data = pd.read_csv(file_path)

# 2. Data Exploration
print(data.info())  # Check data types, null values
print(data.describe())  # Statistical summary of numeric columns
print(data.head())  # First few rows of the dataset

# 3. Handling Duplication of Data
data = data.drop_duplicates()
print("Duplicates removed, if any.")

# 4. Handling Missing Values
# Option 1: Drop rows with any missing values
data = data.dropna()

# Option 2: Impute missing values for numerical columns
# data['column_name'] = data['column_name'].fillna(data['column_name'].mean())

# Check for missing values after handling
print(data.isnull().sum())

# 5. Handling Categorical Data
# Identify categorical columns
categorical_cols = data.select_dtypes(include=['object']).columns

# Label Encoding for ordinal categorical columns (replace with appropriate columns)
label_encoder = LabelEncoder()
for col in categorical_cols:
    data[col] = label_encoder.fit_transform(data[col])

# One-Hot Encoding for nominal categorical columns (use drop_first=True to avoid dummy trap)
data = pd.get_dummies(data, drop_first=True)

# 6. Splitting the Dataset into Training and Testing Sets
X = data.drop('review', axis=1) 
y = data['rating']  

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# 7. Feature Scaling
# Standardization
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Alternatively, use Normalization
# normalizer = MinMaxScaler()
# X_train = normalizer.fit_transform(X_train)
# X_test = normalizer.transform(X_test)

print("Data preprocessing complete.")


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5479 entries, 0 to 5478
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  5479 non-null   int64 
 1   rating      5479 non-null   int64 
 2   review      5478 non-null   object
dtypes: int64(2), object(1)
memory usage: 128.5+ KB
None
        Unnamed: 0       rating
count  5479.000000  5479.000000
mean   2739.000000     3.161343
std    1581.795393     1.782197
min       0.000000     1.000000
25%    1369.500000     1.000000
50%    2739.000000     4.000000
75%    4108.500000     5.000000
max    5478.000000     5.000000
   Unnamed: 0  rating                                             review
0           0       5                                               nice
1           1       5  best biryani , so supportive staff of outlet ,...
2           2       4     delivery boy was very decent and supportive.👌👍
3           3       1  worst biryani i have tasted in my 

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# Load the dataset
file_path = 'C:\\Users\\Avantika Singh\\Downloads\\zomato_reviews.csv'  
data = pd.read_csv(file_path)

# Separate features (X) and target variable (y)

X = data.drop('review', axis=1)
y = data['rating']

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

### Simple Linear Regression (assuming X has only one feature for simple regression)
# Create and fit the model
simple_lr = LinearRegression()
simple_lr.fit(X_train, y_train)

# Predictions
y_pred_simple = simple_lr.predict(X_test)

# Evaluation Metrics
mse_simple = mean_squared_error(y_test, y_pred_simple)
rmse_simple = np.sqrt(mse_simple)
mae_simple = mean_absolute_error(y_test, y_pred_simple)
r2_simple = r2_score(y_test, y_pred_simple)

print("Simple Linear Regression Metrics:")
print(f"MSE: {mse_simple}, RMSE: {rmse_simple}, MAE: {mae_simple}, R2: {r2_simple}")

### Multiple Linear Regression
# Create and fit the model
multi_lr = LinearRegression()
multi_lr.fit(X_train, y_train)

# Predictions
y_pred_multi = multi_lr.predict(X_test)

# Evaluation Metrics
mse_multi = mean_squared_error(y_test, y_pred_multi)
rmse_multi = np.sqrt(mse_multi)
mae_multi = mean_absolute_error(y_test, y_pred_multi)
r2_multi = r2_score(y_test, y_pred_multi)

print("\nMultiple Linear Regression Metrics:")
print(f"MSE: {mse_multi}, RMSE: {rmse_multi}, MAE: {mae_multi}, R2: {r2_multi}")

### Polynomial Regression
# Transform features to polynomial features
poly = PolynomialFeatures(degree=2)  # Adjust degree as needed
X_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)

# Create and fit the model on transformed features
poly_lr = LinearRegression()
poly_lr.fit(X_poly, y_train)

# Predictions
y_pred_poly = poly_lr.predict(X_test_poly)

# Evaluation Metrics
mse_poly = mean_squared_error(y_test, y_pred_poly)
rmse_poly = np.sqrt(mse_poly)
mae_poly = mean_absolute_error(y_test, y_pred_poly)
r2_poly = r2_score(y_test, y_pred_poly)

print("\nPolynomial Regression Metrics:")
print(f"MSE: {mse_poly}, RMSE: {rmse_poly}, MAE: {mae_poly}, R2: {r2_poly}")


Simple Linear Regression Metrics:
MSE: 2.933486520840681e-31, RMSE: 5.416167021834428e-16, MAE: 3.5352904707498144e-16, R2: 1.0

Multiple Linear Regression Metrics:
MSE: 2.933486520840681e-31, RMSE: 5.416167021834428e-16, MAE: 3.5352904707498144e-16, R2: 1.0

Polynomial Regression Metrics:
MSE: 1.7753661238621958e-24, RMSE: 1.3324286561997216e-12, MAE: 1.0611465072415482e-12, R2: 1.0


In [25]:
# Evaluate the model with zero_division handling
for model_name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    conf_matrix = confusion_matrix(y_test, y_pred)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted', zero_division=0)
    recall = recall_score(y_test, y_pred, average='weighted', zero_division=0)
    f1 = f1_score(y_test, y_pred, average='weighted', zero_division=0)

    print(f"\nModel: {model_name}")
    print("Confusion Matrix:")
    print(conf_matrix)
    print(f"Accuracy: {accuracy:.2f}")
    print(f"Precision: {precision:.2f}")
    print(f"Recall: {recall:.2f}")
    print(f"F1-Score: {f1:.2f}")
    print("Classification Report:")
    print(classification_report(y_test, y_pred, zero_division=0))



Model: Logistic Regression
Confusion Matrix:
[[125   0   0   0 275]
 [ 18   0   0   0  44]
 [ 25   0   0   0  74]
 [ 32   0   0   0  49]
 [104   0   0   0 350]]
Accuracy: 0.43
Precision: 0.33
Recall: 0.43
F1-Score: 0.36
Classification Report:
              precision    recall  f1-score   support

           1       0.41      0.31      0.36       400
           2       0.00      0.00      0.00        62
           3       0.00      0.00      0.00        99
           4       0.00      0.00      0.00        81
           5       0.44      0.77      0.56       454

    accuracy                           0.43      1096
   macro avg       0.17      0.22      0.18      1096
weighted avg       0.33      0.43      0.36      1096


Model: K-Nearest Neighbors
Confusion Matrix:
[[231   4  11  21 133]
 [ 41   2   2   3  14]
 [ 44   2   9   5  39]
 [ 41   4   0   5  31]
 [170   7  25  12 240]]
Accuracy: 0.44
Precision: 0.41
Recall: 0.44
F1-Score: 0.42
Classification Report:
              precision

In [ ]:
# Evaluate the model with zero_division handling
for model_name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    conf_matrix = confusion_matrix(y_test, y_pred)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted', zero_division=0)
    recall = recall_score(y_test, y_pred, average='weighted', zero_division=0)
    f1 = f1_score(y_test, y_pred, average='weighted', zero_division=0)

    print(f"\nModel: {model_name}")
    print("Confusion Matrix:")
    print(conf_matrix)
    print(f"Accuracy: {accuracy:.2f}")
    print(f"Precision: {precision:.2f}")
    print(f"Recall: {recall:.2f}")
    print(f"F1-Score: {f1:.2f}")
    print("Classification Report:")
    print(classification_report(y_test, y_pred, zero_division=0))



Model: Logistic Regression
Confusion Matrix:
[[125   0   0   0 275]
 [ 18   0   0   0  44]
 [ 25   0   0   0  74]
 [ 32   0   0   0  49]
 [104   0   0   0 350]]
Accuracy: 0.43
Precision: 0.33
Recall: 0.43
F1-Score: 0.36
Classification Report:
              precision    recall  f1-score   support

           1       0.41      0.31      0.36       400
           2       0.00      0.00      0.00        62
           3       0.00      0.00      0.00        99
           4       0.00      0.00      0.00        81
           5       0.44      0.77      0.56       454

    accuracy                           0.43      1096
   macro avg       0.17      0.22      0.18      1096
weighted avg       0.33      0.43      0.36      1096


Model: K-Nearest Neighbors
Confusion Matrix:
[[231   4  11  21 133]
 [ 41   2   2   3  14]
 [ 44   2   9   5  39]
 [ 41   4   0   5  31]
 [170   7  25  12 240]]
Accuracy: 0.44
Precision: 0.41
Recall: 0.44
F1-Score: 0.42
Classification Report:
              precision

In [26]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

# Initialize and train Decision Tree Classifier (Gini)
decision_tree_gini = DecisionTreeClassifier(criterion='gini')
decision_tree_gini.fit(X_train, y_train)
y_pred_gini = decision_tree_gini.predict(X_test)

# Evaluate Decision Tree Classifier (Gini)
print("\nDecision Tree (Gini) Classification Report:")
print(classification_report(y_test, y_pred_gini))

# Initialize and train Decision Tree Classifier (Information Gain)
decision_tree_entropy = DecisionTreeClassifier(criterion='entropy')
decision_tree_entropy.fit(X_train, y_train)
y_pred_entropy = decision_tree_entropy.predict(X_test)

# Evaluate Decision Tree Classifier (Information Gain)
print("\nDecision Tree (Entropy) Classification Report:")
print(classification_report(y_test, y_pred_entropy))



Decision Tree (Gini) Classification Report:
              precision    recall  f1-score   support

           1       0.41      0.40      0.40       400
           2       0.06      0.06      0.06        62
           3       0.12      0.13      0.13        99
           4       0.11      0.11      0.11        81
           5       0.54      0.54      0.54       454

    accuracy                           0.39      1096
   macro avg       0.25      0.25      0.25      1096
weighted avg       0.40      0.39      0.39      1096


Decision Tree (Entropy) Classification Report:
              precision    recall  f1-score   support

           1       0.41      0.40      0.40       400
           2       0.06      0.06      0.06        62
           3       0.12      0.13      0.13        99
           4       0.11      0.11      0.11        81
           5       0.54      0.54      0.54       454

    accuracy                           0.39      1096
   macro avg       0.25      0.25     